### ISSUE TITLE
A few questions...

### ISSUE THREAD

**Issue by NigelGreenway** [thephpleague/tactician-container#1]
Hi,

Just setting up the base repo against the League skeleton, in terms of the namespace is `League\TacticianContainer` for the autoloader correct? Also, what is the description and keywords wanted?

Will be finally adding it over the next few days.

 Nigel

**Comment by NigelGreenway** [comment]
Also, what version are we to release this under?

**Comment by rosstuck** [comment]
Hi Nigel! Good move with the League Skeleton, I've enabled Travis so once the .travis.yml gets merged in, we'll have build info as well.

For namespace, use `League\Tactician\Container` and for package name `league/tactician-container`. 

For description, maybe "Tactician integration with the PHP League DI container" and keywords "tactician, di, container, league". Feel free to play around with those though. :)

**Comment by NigelGreenway** [comment]
@rosstuck So, finally got round to working on it. I only have 2 tests at the moment and due to my mind being fried at work at the moment I can not think of any more to add so if you think that there should be let me know.

I also haven't added a version number, was not sure if it was to be released as v1.0 or below?

It can be found [here](http://github.com/nigelgreenway/tactician-container) for review.

**Comment by rosstuck** [comment]
Hey, looking good! Can you open a PR from your repo to this one? I'll add a couple of comments in there about some things to spruce up and then I think we can release an initial 0.1 and see how it looks from there? :)

Some of the open points I see are:
- Just let the League\Container exceptions bubble up, you don't have to do anything with them. That would let you remove the MissingContainerException
- You can remove the MissingCommandException and just throw the MissingHandlerException that's included in Tactician core.
- We require PHP 5.5 and above so you can shorten a lot of the test config by using the class constant. :smile: 

That's easier to discuss in the PR though, so just send one over and we can go from there, looks like the home-stretch now. :smile:

**Comment by rosstuck** [comment]
@NigelGreenway Seems like we've got this ticket cleared off, so going to close it now. :smile_cat:
