### ISSUE TITLE
php 7 and 7.1 on travis

### ISSUE THREAD

**Issue by lunika** [thephpleague/tactician-container#11]
For now php 7 is in allow failure on travis. I don't use this plugin si I don't know if it's normal or not.

Otherwise I can remove the allow failure case and add php 7.1

WDYT ?

**Comment by rosstuck** [comment]
Just went ahead and made PHP 7 and 7.1 required. 7 was still in RC when it was added, hence the allow_failures.

In the meantime, that appears to be the last of 'em! Thanks a ton for all your help, we did it!
![thank you](https://media.giphy.com/media/3oEduJnper1UdNqreg/giphy.gif)
