### ISSUE TITLE
Rewrite docs to emphasize container-interop

### ISSUE THREAD

**Issue by rosstuck** [thephpleague/tactician-container#8]
With the merge of #6, this package is beginning to pivot towards focusing on the container-interop interface, rather than specifically League\Container, which is awesome. Good thing the name was already kinda vague. :wink: Thanks @spekkionu!

The code changes have been merged in but before I tag a release on it, the README needs a rewrite and the composer/packagist description needs an update. I probably won't get to this until the second half of November due to work/conference/life. If anyone else wants to take point on this, that'd be awesome. Otherwise, I'll get to it as soon as I can. Thanks!

**Comment by rosstuck** [comment]
FYI: We also need to update the page on the Tactician site ( http://tactician.thephpleague.com/plugins/league-container/ ). This can be found in the main Tactician repo on the gh-pages branch.

**Comment by hannesvdvreken** [comment]
I hope a release can be made now?

**Comment by rosstuck** [comment]
Yup, working on that as we speak. :)

**Comment by hannesvdvreken** [comment]
[0.7](https://github.com/thephpleague/tactician-container/releases/tag/0.7), following tactician?

**Comment by rosstuck** [comment]
Yeah, and to also convey some level of internal maturity, at least. Unless
there are any major complaints, I imagine it'll hit 1.0 before long.

**Comment by hannesvdvreken** [comment]
:+1:
